// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRo20_Hfk5CjpH_JPE2oUKD_vSXGQoh1Y',
    appId: '1:699471060311:android:90f5b815287bff6dd7f212',
    messagingSenderId: '699471060311',
    projectId: 'gadget-shop-c06b4',
    storageBucket: 'gadget-shop-c06b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqIeeCXtiIzl0dd_5XmCnYQBPT44KFIZ8',
    appId: '1:699471060311:ios:14107d793e4ca4c2d7f212',
    messagingSenderId: '699471060311',
    projectId: 'gadget-shop-c06b4',
    storageBucket: 'gadget-shop-c06b4.appspot.com',
    androidClientId: '699471060311-s8vv8fdeu4jitselbdjfngjk7j5788bt.apps.googleusercontent.com',
    iosClientId: '699471060311-q5uvh6sn4841ubg9j2jku129d39l0ejc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNtTen',
  );
}
